# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "install.sh"
  config.vm.synced_folder "onos", "/home/ubuntu/nms-aware-onos"
  config.vm.hostname = "onos"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end

  
end
