# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "install.sh"
  config.vm.synced_folder "nms-aware-onos", "/home/ubuntu/nms-aware-onos", create: true
  config.vm.hostname = "onos"
  config.vm.network "private_network", ip: "192.168.33.20"
  
  config.vm.provider "virtualbox" do |v|
	v.name = "Ubuntu_Xenial64_NMS_Aware_ONOS"
    v.memory = 4096
    v.cpus = 2
  end
  
end
