# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "install.sh"
  config.vm.synced_folder "scripts", "/home/ubuntu/scripts", create: true
  config.vm.hostname = "nms"
  config.vm.network "private_network", ip: "192.168.10.20"
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  
end
